
include: "modules/settings/paths.smk"
include: "modules/settings/sample_table.smk"
include: "modules/settings/constants.smk"

include: "modules/coverage/contig_cov.smk"

include: "modules/rdna/ribotin.smk"

include: "modules/regions/hla/extract.smk"

rule run_all:
    input:
        everything = [
            rules.run_all_issue_tracks.input.stats,
            rules.extract_hla_sequences.output.table_comp,
            rules.extract_hla_sequences.output.all_seqs
        ]
